### ISSUE TITLE
[meta] Documentation, Documentation, Documentation

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/dmon#2]
It would be great to take advantage of the fact that GitHub renders Markdown files to add some documentation to the repository. In turn, the Markdown files could be themselves used to assemble a mini-site using e.g. [pandoc](http://pandoc.org).

It would be nice to cover the following:

* [ ] Philosophy.
* [ ] Examples:
  - [ ] How to convert any normal program into a daemon using `dmon` (hint: it's trivial!).
  - [ ] How to use with `tcpserver`, `ipsvd`, or other socket server in the style of [ucspi-tcp](http://cr.yp.to/ucspi-tcp.html).
  - [ ] Using `libnofork.so` to prevent pesky daemons from forkin.
* [ ] Integrating with other systems:
  - [ ] sysvinit: How to use `dmon` in an init script.
  - [ ] systemd: How to use `dmon` in an unit.
